### ISSUE TITLE
Next - Cannot find userId object

### ISSUE THREAD

**Issue by genofire** [SfietKonstantin/friends-sailfish#5]
After Login,
 it stay - please get in touch with the developer.
From console:

```
Cannot find userId object
```

In `.config/harbour-friends/Friends.conf` is a `userId` attribute with a 9 digit number.

Version  1.50.1 from OBS-Next

**Comment by SfietKonstantin** [comment]
hum ... Maybe I should enable dumping everything that is retrieved from Facebook.
Maybe Facebook changed something for their login procedure.

Please stay in touch.

**Comment by genofire** [comment]
With pleasur :)

```
---
| SailfishOS 1.1.6.27 (Aaslakkajärvi) (armv7hl)
'---
[nemo@Jolla ~]$ harbour-friends
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Way
land-EGL
[D] expression for onErrorMessageChanged:53 - ==== Error ====
Cannot find userId object
===============
[D] expression for onErrorMessageChanged:53 - ==== Error ====
Cannot find userId object
===============
```
